application: mrb-resume
version: 2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /files
  static_dir: files
- url: /.*
  script: python/main.py

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest